global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'w2w-share'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['w2w-share:8080']
        labels:
          application: 'w2w-share'
